name: API Automation CI/CD

on: [push, pull_request]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Install Maven dependencies
        run: mvn install

      - name: Run API tests
        run: mvn test

      - name: Generate Maven site (reports)
        run: mvn site
